Bose | Quiet comfort 35 Wireless II / Black:
  Link: https://www.bose.com/en_us/products/headphones/over_ear_headphones/quietcomfort-35-wireless-ii.html
  Brand: BOSE
  Model: Quiet comfort 35 Wireless II / Black
  SKU: 789564
  Category: Headphones
  Sub-category: Wireless
ASUS | ROG G701VI-XS72K OC Edition:
  Link: http://store.asus.com/us/item/201702AM030000001
  Brand: ASUS
  Model: ROG G701VI-XS72K OC Edition
  SKU: 201702AM030000001
  Category: Laptop
  Sub-category: None
ASUS | ROG Ranger Backpack:
  Link: https://store.asus.com/us/item/201701AM100000021
  Brand: ASUS
  Model: ROG Ranger Backpack
  SKU: 201701AM100000021
  Category: Laptop
  Sub-category: Backpack
